import Head from "next/head";

export default function menu({ children }) {
  return (
    <Head>
      <title>{children}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
